### ISSUE TITLE
 Reaching out to you for - api.ai Agent files for your Tasks repo

### ISSUE THREAD

**Issue by kshitizshankar** [xVir/xvir.github.com#1]
abaker from Tasks repo redirected me to you -
"Check out https://github.com/xVir/tasks, I believe this is the work that the youtube demo was based off of"
I think the issues in that repo are disabled, so am trying to reach out to you through this.

I am getting started with Api.ai and wanted to play around with the Tasks example. I am trying to emulate a similar thing for a Hybrid app. 
I looked through the code base and couldn't find any reference to the API.AI
(I came here through https://www.youtube.com/watch?v=kz_xCEPNJGw)

Can you help me in getting the agent for the api.ai which I can import in the UI and try it out?

Thanks a lot.

**Comment by xVir** [comment]
Hi, @kshitizshankar, I enable issues in the https://github.com/xVir/tasks and copy the issue there - https://github.com/xVir/tasks/issues/1

**Comment by kshitizshankar** [comment]
Hi @xVir Sure, thanks! Will reply there in that case..
